PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX chebi: <http://purl.obolibrary.org/obo/chebi/>
PREFIX chebidb: <http://purl.obolibrary.org/obo/CHEBI_>
PREFIX chebirel: <http://purl.obolibrary.org/obo/CHEBI#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX bp3: <http://www.biopax.org/release/biopax-level3.owl#>
PREFIX reactome: <http://www.reactome.org/biopax/95/48887#>
PREFIX abstraction:<http://abstraction/#>

#CONSTRUCT {
#  ?enzymeRefA abstraction:CatalysisPrecedes ?enzymeRefB
#}
#SELECT DISTINCT ?reaction1 ?connectingMolecule ?connectingMoleculeID ?reaction2 ?enzymeRefA ?enzymeRefB
SELECT DISTINCT ?enzymeRefA ?enzymeRefB
WHERE {
  ?reaction1 rdf:type/(rdfs:subClassOf*) bp3:Conversion .
  ?reaction1 bp3:left ?leftMolecule1 .
  ?leftMolecule1 rdf:type bp3:SmallMolecule .
  # get the connecting molecule
  ?reaction1 bp3:right ?connectingMolecule .
  ?connectingMolecule rdf:type bp3:SmallMolecule .
  ?connectingMolecule bp3:entityReference ?connectingMoleculeRef .
  ?connectingMoleculeRef bp3:xref ?connectingMoleculeXref .
  ?connectingMoleculeXref rdf:type bp3:UnificationXref .
  ?connectingMoleculeXref bp3:db "ChEBI" .
  ?connectingMoleculeXref bp3:id ?connectingMoleculeID .
  #FILTER NOT EXISTS { ?connectingMoleculeXref bp3:id ?blacklist . }
  FILTER (?connectingMoleculeID NOT IN ("CHEBI:15377", "CHEBI:24636", "CHEBI:15378", "CHEBI:15379", "CHEBI:57783",
    "CHEBI:13392", "CHEBI:16474", "CHEBI:58349", "CHEBI:18009", "CHEBI:13390",
    "CHEBI:25523", "CHEBI:25524", "CHEBI:30616", "CHEBI:15422", "CHEBI:16761",
    "CHEBI:456216", "CHEBI:57945", "CHEBI:16908", "CHEBI:57540", "CHEBI:15846",
    "CHEBI:16526", "CHEBI:29888", "CHEBI:35782", "CHEBI:68836", "CHEBI:18361",
    "CHEBI:43474", "CHEBI:35780", "CHEBI:18367", "CHEBI:26078", "CHEBI:77740",
    "CHEBI:28931", "CHEBI:58307", "CHEBI:17877", "CHEBI:17552", "CHEBI:58189",
    "CHEBI:37565", "CHEBI:15996"))
  ?reaction2 bp3:left ?connectingMolecule .
  ?reaction2 rdf:type/(rdfs:subClassOf*) bp3:Conversion .
  ?reaction2 bp3:right ?rightMolecule2 .
  ?rightMolecule2 rdf:type bp3:SmallMolecule .

  # Get catalysis of the first reaction
  ?catalysis1 bp3:controlled ?reaction1 .
  ?catalysis1 (rdf:type/rdfs:subClassOf*) bp3:Control .
  ?catalysis1 bp3:controller/((bp3:component|bp3:memberPhysicalEntity)*) ?enzymeProtA .
  ?enzymeProtA rdf:type bp3:Protein .
  ?enzymeProtA bp3:entityReference ?enzymeRefA .
  ?enzymeRefA rdf:type/(rdfs:subClassOf*) bp3:EntityReference .

  # get catalysis of the second reaction
  ?catalysis2 bp3:controlled ?reaction2 .
  ?catalysis2 (rdf:type/rdfs:subClassOf*) bp3:Control .
  ?catalysis2 bp3:controller/((bp3:component|bp3:memberPhysicalEntity)*) ?enzymeProtB .
  ?enzymeProtB rdf:type bp3:Protein .
  ?enzymeProtB bp3:entityReference ?enzymeRefB .
  ?enzymeRefB rdf:type/(rdfs:subClassOf*) bp3:EntityReference .
  
  FILTER (?enzymeRefA != ?enzymeRefB)
  FILTER (?leftMolecule1 != ?rightMolecule2)
  FILTER (?leftMolecule1 != ?connectingMolecule)
  FILTER (?rightMolecule2 != ?connectingMolecule)
}